Ques 1

In [1]:
import numpy as np
list_=['1','2','3','4','5']
array_list=np.array(object=list_)

Yes, there is a difference in the datatype of variables list_ and array_list. The list_ variable is a python list, and the array_list variable is a Numpy array. The elements in the list_ are strings , whereas the elements in the array_list are integers, as Numpy NumPy automatically infers the data type when creating an array from a list of strings.

In [2]:
print('Data type of list_ :', type(list_))
print('Data type of array_list:',type(array_list))

Data type of list_ : <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


Ques 2

In [3]:
print('Data type of elements in list_ :')
for i in list_:
    print(type(i))

Data type of elements in list_ :
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [4]:
print("\nData types of elements in 'array_list':")
for element in array_list:
    print(type(element))



Data types of elements in 'array_list':
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


Ques 3

No, there will be a difference in the data type of the elements present in list_ and array_list after the change.  The list_ variable is a python list, and the array_list variable is a Numpy array. However the every elements datatype of array_list will be converted to integers.

In [5]:
array_list=np.array(object=list_,dtype=int)
print('Data type of list_ :', type(list_))
print('Data type of array_list:',type(array_list))

Data type of list_ : <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


In [6]:
print("\nData types of elements in 'array_list':")
for element in array_list:
    print(type(element))


Data types of elements in 'array_list':
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


Ques 4

In [7]:
import numpy as np
num_list=[[1,2,3],[4,5,6]]
num_array=np.array(object=num_list)

In [8]:
array_size=num_array.size
print('Size of the array:',array_size)

Size of the array: 6


In [9]:
array_shape=num_array.shape
print('Shape of the array:', array_shape)

Shape of the array: (2, 3)


Ques 5

In [10]:
mat_3=np.zeros((3,3))
print('Matrix:',mat_3)
print('Matrix size:',mat_3.size)
print('Matrix shape:',mat_3.shape)

Matrix: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Matrix size: 9
Matrix shape: (3, 3)


Ques 6

In [11]:
Idn_mat=np.eye(5)
print('Identity matrix:',Idn_mat)

Identity matrix: [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
